title: ELSM
description: Naila Hamid, Nazar Khan, Arbish Akram
description: Computer Vision & Machine Learning Group, Department of Computer Science, University of the Punjab, Lahore, Pakistan
theme: jekyll-theme-minimal
